<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="2" hostname="panxideMac-mini.local" name="com.wljs.testcase.RegressionTesting" tests="3" failures="0" timestamp="07 Jan 2020 07:43:50 GMT" time="0.020" errors="1">
  <testcase name="loginApp" time="0.020" classname="com.wljs.testcase.RegressionTesting">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.wljs.testcase.IosExeuteTestCase.exeuteTestCase(IosExeuteTestCase.java:31)
at com.wljs.testcase.RegressionTesting.chooseTestCase(RegressionTesting.java:116)
at com.wljs.testcase.RegressionTesting.loginApp(RegressionTesting.java:104)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.wljs.app.ExecuteTestng.call(ExecuteTestng.java:36)
at com.wljs.app.ExecuteTestng.call(ExecuteTestng.java:17)
at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
at java.util.concurrent.FutureTask.run(FutureTask.java)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
]]>
    </error>
  </testcase> <!-- loginApp -->
  <testcase name="viewProduct" classname="com.wljs.testcase.RegressionTesting">
    <skipped/>
  </testcase> <!-- viewProduct -->
  <testcase name="bootPageApp" classname="com.wljs.testcase.RegressionTesting">
    <skipped/>
  </testcase> <!-- bootPageApp -->
</testsuite> <!-- com.wljs.testcase.RegressionTesting -->
